##
# Makefile for Common Operations
#
# @author Rafael Lima
##

###############################################################################
# Variables
###############################################################################

# Compiler Options
CC := ghdl
CC_FLAGS :=

# Target files
VHDL_DIR := src
VHDL_SRC := $(wildcard ${VHDL_DIR}/*.vhd)
VHDL_OBJ := $(VHDL_SRC:.vhd=.o)
VHDL_CSRC := $(VHDL_SRC:.vhd=.cc)

###############################################################################
# Rules
###############################################################################

# Man Rule
.PHONY: ALL
ALL: $(VHDL_OBJ)

# Print help for all commands
.PHONY: help
help:
	@echo "Use: make [OPTION]\n\nOPTIONS"
	@sed Makefile -n -e "N;s/^# \(.*\)\n.PHONY:\(.*\)/ \2:\1/p;D" | column -ts:
	@echo ""

# Compile and simulate hello_world example
.PHONY: helloworld
helloworld: src/00_hello_world/hello_world.vhd
	cd src/00_hello_world
	$(CC) -a $^
	$(CC) -e hello_world
	$(CC) -r hello_world

# Compile and simulate full adder example
.PHONY: adder
adder: src/02_adder/adder.vhd src/02_adder/adder_tb.vhd
	cd src/02_adder
	$(CC) -a $^
	$(CC) -e adder_tb
	$(CC) -r adder_tb

# Remove Generated Files
.PHONY: clear
clean:
	rm -vrf $(VHDL_OBJ) $(VHDL_CSRC)

###############################################################################
# Documentation Rules
# - Generated by Doxygen + Dot
###############################################################################

# Generate Doxygen Documentation
.PHONY: docs
docs: Doxyfile
	doxygen Doxyfile

# Remove Generated Documentation files
.PHONY: clean-docs
clean-docs:
	rm -vrf docs/*
