##
# Makefile for Common Operations
#
# @author Rafael Lima
##

###############################################################################
# Variables
###############################################################################

# Compiler Options
CC := ghdl
CC_FLAGS :=


###############################################################################
# Rules
###############################################################################

# Man Rule
.PHONY: ALL
ALL: hello_world adder

# Print help for all commands
.PHONY: help
help:
	@echo "Use: make [OPTION]\n\nOPTIONS"
	@sed Makefile -n -e "N;s/^# \(.*\)\n.PHONY:\(.*\)/ \2:\1/p;D" | column -ts:
	@echo ""

# Compile and simulate hello_world example
.PHONY: hello_world
hello_world: src/00_hello_world/hello_world.vhd
	$(CC) -a $^
	$(CC) -e hello_world
	$(CC) -r hello_world

# Compile and simulate full adder example
.PHONY: adder
adder: src/02_adder/adder.vhd src/02_adder/adder_tb.vhd
	$(CC) -a $^
	$(CC) -e adder_tb
	$(CC) -r adder_tb

# Remove Generated Files
.PHONY: clear
clean:
	rm -vrf work-obj93.cf

###############################################################################
# Documentation Rules
# - Generated by Doxygen + Dot
###############################################################################

# Generate Doxygen Documentation
.PHONY: docs
docs: Doxyfile
	doxygen Doxyfile

# Remove Generated Documentation files
.PHONY: clean-docs
clean-docs:
	rm -vrf docs/*
