##
# Makefile for Common Operations
#
# @author Rafael Lima
##

###############################################################################
# Variables
###############################################################################

# Compiler Options
CC := ghdl
CC_FLAGS :=

# Target files
VHDL_DIR := src
VHDL_SRC := $(wildcard ${VHDL_DIR}/*.vhd)
VHDL_OBJ := $(VHDL_SRC:.vhd=.o)
VHDL_CSRC := $(VHDL_SRC:.vhd=.cc)

###############################################################################
# Variables
###############################################################################

# Man Rule
.PHONY: ALL
ALL: $(VHDL_OBJ)

# Print help for all commands
.PHONY: help
help:
	@echo "Use: make [OPTION]\n\nOPTIONS"
	@sed Makefile -n -e "N;s/^# \(.*\)\n.PHONY:\(.*\)/ \2:\1/p;D" | column -ts:
	@echo ""

%.o: %.vhd
	$(CC) -a $< $(CC_FLAGS)

# Remove Generated Files
.PHONY: clear
clean:
	rm -vrf $(VHDL_OBJ) $(VHDL_CSRC)

###############################################################################
# Documentation Rules
# - Generated by Doxygen + Dot
###############################################################################

# Generate Doxygen Documentation
.PHONY: docs
docs: Doxyfile
	doxygen Doxyfile

# Remove Generated Documentation files
.PHONY: clean-docs
clean-docs:
	rm -vrf docs/*
